name: elpmi_profile_repository
description: Dart package which manages the GraphQL calls for elpmi profile
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  # cache:
  #   path: ../cache
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   mocktail: ^0.3.0
#   plugin_platform_interface: ^2.1.3
#   very_good_analysis: ^3.1.0