// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdW8H0Q5JRvudZCBJ6eMc1p31EY54ytQo',
    appId: '1:357440149806:web:d0246f7f5a6312d65c42bf',
    messagingSenderId: '357440149806',
    projectId: 'protos-901f9',
    authDomain: 'protos-901f9.firebaseapp.com',
    storageBucket: 'protos-901f9.appspot.com',
    measurementId: 'G-W9VN23N3G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPkWTAXu_pX0npadOkKRq9km9hnUsTZWQ',
    appId: '1:357440149806:android:b0c34f0e561f6ca65c42bf',
    messagingSenderId: '357440149806',
    projectId: 'protos-901f9',
    storageBucket: 'protos-901f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjUjWO7PpyTSDlFVaIBLig4_I8sz7tgiw',
    appId: '1:357440149806:ios:f658fe8f5b1ad6ae5c42bf',
    messagingSenderId: '357440149806',
    projectId: 'protos-901f9',
    storageBucket: 'protos-901f9.appspot.com',
    iosClientId: '357440149806-tfn684lg00igfj4r0krsuei0nuul4n2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontFlutter',
  );
}
